### ISSUE TITLE
 latest release of ya-sb-router seems  broken deb

### ISSUE THREAD

**Issue by tworec** [golemfactory/ya-service-bus#31]
The latest release of ya-sb-router seems to include a broken deb package, goth tests are failing on building their yagna docker image with the following error:
dpkg: error processing archive /ya-sb-router_v0.4.6_amd64.deb (--unpack): conffile name 'etc/ya-sb-router.conf' is not an absolute pathname

Reported by @zakaprov

**Comment by kmazurek** [comment]
This is related to a change introduced in [`dpkg` version `1.20.1`](https://github.com/guillemj/dpkg/blob/68ab722604217d3ab836276acfc0ae1260b28f5f/debian/changelog#L393) which changes how "relative" paths in deb packages are treated.
This change is reflected in `cargo deb` with this PR https://github.com/mmstick/cargo-deb/pull/173, however there's no release which includes it yet.

I'd suggest we update `cargo deb` in this repo once it's possible and do a patch release. For the time being I can pin the Docker images we use in [`goth`](https://github.com/golemfactory/goth) to an earlier version of Debian, so that they use `dpkg` version `1.19.x`.

**Comment by kmazurek** [comment]
This has been resolved in [`ya-service-bus` 0.4.7 release](https://github.com/golemfactory/ya-service-bus/releases/tag/v0.4.7). Also, the version of the `debian` image used in `goth` tests has been pinned to a specific SHA (https://github.com/golemfactory/goth/pull/507) to prevent potential breaking updates in the future.

**Comment by tworec** [comment]
@prekucki thx a lot for a speedy fix. 
@zakaprov muchas gracias for verification and closing
